# Generated by Django 4.0.3 on 2022-05-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adicionarMedicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.TextField()),
                ('Especializacao', models.TextField()),
            ],
            options={
                'db_table': 'adicionarMedicos',
            },
        ),
    ]
