# Generated by Django 4.0.4 on 2022-05-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Especializacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='adicionarMedicos',
        ),
    ]
