# Generated by Django 4.0.4 on 2022-05-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0002_medico_delete_adicionarmedicos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='Especializacao',
            new_name='Especialidade',
        ),
    ]
