# Generated by Django 4.0.4 on 2022-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0005_parceiros_alter_noticia_detalhes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeConvenio', models.CharField(max_length=100)),
            ],
        ),
    ]
