# Generated by Django 4.0.4 on 2022-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0011_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeTransparencia', models.CharField(max_length=100)),
                ('PdfTransparencia', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
