# Generated by Django 4.0.4 on 2022-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0016_alter_noticia_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='Data',
            field=models.DateField(null=True),
        ),
    ]
