# Generated by Django 4.0.4 on 2022-05-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0017_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Corpo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
