# Generated by Django 4.0.4 on 2022-05-31 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0018_alter_noticia_corpo_alter_noticia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='Data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='Subtitulo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
