# Generated by Django 4.0.4 on 2022-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0019_alter_noticia_data_alter_noticia_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConselhoDeliberativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeConselho', models.CharField(max_length=100)),
                ('CargoConselho', models.CharField(max_length=50)),
                ('FotoConselho', models.ImageField(blank=True, null=True, upload_to='ConselhoDeliberativo')),
            ],
        ),
        migrations.CreateModel(
            name='DiretoriaExecutiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeDiretorExecutivo', models.CharField(max_length=100)),
                ('CargoDiretorExecutivo', models.CharField(max_length=50)),
                ('FotoDiretorExecutivo', models.ImageField(blank=True, null=True, upload_to='DiretoriaExecutiva')),
            ],
        ),
    ]
