# Generated by Django 4.0.4 on 2022-06-03 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0020_conselhodeliberativo_diretoriaexecutiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaleConosco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sobrenome', models.CharField(max_length=50)),
                ('Telefone', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('Assunto', models.CharField(max_length=50)),
                ('Mensagem', models.CharField(max_length=350)),
            ],
        ),
    ]
