# Generated by Django 4.0.4 on 2022-06-03 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0021_faleconosco'),
    ]

    operations = [
        migrations.AddField(
            model_name='faleconosco',
            name='operadora',
            field=models.CharField(choices=[('TIM', 'Tim'), ('VIVO', 'Vivo'), ('CLARO', 'Claro')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='faleconosco',
            name='Assunto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faleconosco',
            name='Mensagem',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
