# Generated by Django 4.0.5 on 2022-06-03 23:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0022_faleconosco_operadora_alter_faleconosco_assunto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faleconosco',
            name='Assunto',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faleconosco',
            name='Telefone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
    ]
