# Generated by Django 4.0.5 on 2022-06-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0023_alter_faleconosco_assunto_alter_faleconosco_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faleconosco',
            name='Assunto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faleconosco',
            name='Mensagem',
            field=models.TextField(),
        ),
    ]
