# Generated by Django 4.0.5 on 2022-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0026_remove_faleconosco_operadora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=150)),
                ('Categoria', models.CharField(max_length=100)),
                ('Foto', models.ImageField(null=True, upload_to='Galeria')),
                ('Descrição', models.CharField(blank=True, max_length=400, null=True)),
                ('Data', models.DateField()),
            ],
        ),
    ]
