# Generated by Django 4.0.5 on 2022-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0028_rename_descrição_galeria_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='NossaMissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=150)),
                ('Missao', models.TextField()),
                ('PoliticadeQualidade', models.TextField()),
                ('Proposito', models.TextField()),
                ('Valores', models.TextField()),
                ('Visao', models.TextField()),
            ],
        ),
    ]
