# Generated by Django 4.0.5 on 2022-06-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0029_nossamissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoRodape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=150)),
                ('Telefone', models.CharField(max_length=14, unique=True)),
                ('Rua', models.TextField()),
                ('Numero', models.CharField(max_length=5)),
                ('Bairro', models.CharField(max_length=80)),
                ('CEP', models.TextField(max_length=9, unique=True)),
                ('Cidade', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Informações Rodapé',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='conselhodeliberativo',
            options={'verbose_name_plural': 'Conselho Deliberativo'},
        ),
        migrations.AlterModelOptions(
            name='convenio',
            options={'verbose_name_plural': 'Convenio'},
        ),
        migrations.AlterModelOptions(
            name='diretoria',
            options={'verbose_name_plural': 'Diretoria'},
        ),
        migrations.AlterModelOptions(
            name='diretoriaexecutiva',
            options={'verbose_name_plural': 'Diretoria Executiva'},
        ),
        migrations.AlterModelOptions(
            name='faleconosco',
            options={'verbose_name_plural': 'Fale Conosco'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'verbose_name_plural': 'galeria'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name_plural': 'Médicos - Guia Médico'},
        ),
        migrations.AlterModelOptions(
            name='nossamissao',
            options={'verbose_name_plural': 'Nossa Missão'},
        ),
        migrations.AlterModelOptions(
            name='parceiros',
            options={'verbose_name_plural': 'Parceiros'},
        ),
        migrations.AlterModelOptions(
            name='premio',
            options={'verbose_name_plural': 'Premios'},
        ),
        migrations.AlterModelOptions(
            name='transparencia',
            options={'verbose_name_plural': 'Transparência'},
        ),
    ]
