# Generated by Django 4.0.5 on 2022-06-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0030_informacaorodape_alter_banner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacaorodape',
            name='CEP',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
