# Generated by Django 4.0.5 on 2022-06-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0031_alter_informacaorodape_cep'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedesSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=150)),
                ('Facebook', models.CharField(max_length=300)),
                ('Twitter', models.CharField(max_length=300)),
                ('Instagram', models.CharField(max_length=300)),
                ('Youtube', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
    ]
