# Generated by Django 4.0.6 on 2022-07-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0032_redessociais'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=150)),
                ('Conteudo', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Historia',
            },
        ),
    ]
