# Generated by Django 4.0.6 on 2022-07-05 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0034_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='Data',
            new_name='DataFim',
        ),
        migrations.RemoveField(
            model_name='eventos',
            name='Duração',
        ),
        migrations.AddField(
            model_name='eventos',
            name='DataInício',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
