# Generated by Django 4.0.6 on 2022-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0035_rename_data_eventos_datafim_remove_eventos_duração_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='HoraFim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventos',
            name='HoraInício',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='DataFim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='DataInício',
            field=models.DateField(),
        ),
    ]
