# Generated by Django 4.0.6 on 2022-07-05 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0036_eventos_horafim_eventos_horainício_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='DataFim',
            field=models.DateField(blank=True, null=True, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='DataInício',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='HoraFim',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Final'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='HoraInício',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Início'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='Informações',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
