# Generated by Django 4.0.6 on 2022-07-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0037_alter_eventos_datafim_alter_eventos_datainício_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='DataInício',
            new_name='DataInicio',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='HoraInício',
            new_name='HoraInicio',
        ),
        migrations.RenameField(
            model_name='eventos',
            old_name='Informações',
            new_name='Informacoes',
        ),
    ]
