# Generated by Django 4.0.6 on 2022-07-08 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0041_remove_doacao_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencia',
            name='CategoriaTransparencia',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transparencia',
            name='DataTransparencia',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='transparencia',
            name='NomeTransparencia',
            field=models.CharField(max_length=150, verbose_name='Títutlo'),
        ),
        migrations.AlterField(
            model_name='transparencia',
            name='PdfTransparencia',
            field=models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='Pdf'),
        ),
    ]
