# Generated by Django 4.0.6 on 2022-07-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0042_transparencia_categoriatransparencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convenio',
            name='NomeConvenio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='CargoDiretoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='NomeDiretoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
