# Generated by Django 4.0.6 on 2022-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0043_alter_convenio_nomeconvenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretoria',
            name='FotoDiretoria',
            field=models.ImageField(blank=True, null=True, upload_to='Diretoria', verbose_name='Foto'),
        ),
    ]
