# Generated by Django 4.0.6 on 2022-07-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0044_alter_diretoria_fotodiretoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Posicao',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
