# Generated by Django 4.0.6 on 2022-07-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0045_banner_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Posicao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
