# Generated by Django 4.0.6 on 2022-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0047_alter_banner_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='Posicao',
            field=models.CharField(blank=True, choices=[('4', '0'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=10, null=True, unique=True, verbose_name='Posição(0 para não exibir)'),
        ),
    ]
