# Generated by Django 4.0.6 on 2022-07-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0048_alter_banner_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='FotoBanner',
            field=models.ImageField(blank=True, null=True, upload_to='Banner', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='NomeBanner',
            field=models.CharField(max_length=100, verbose_name='Nome do Banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='Posicao',
            field=models.CharField(blank=True, choices=[('3', '1'), ('2', '2'), ('1', '3')], max_length=10, null=True, unique=True, verbose_name='Posição (Deixe vazio para não exibir)'),
        ),
        migrations.AlterField(
            model_name='conselhodeliberativo',
            name='CargoConselho',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='conselhodeliberativo',
            name='FotoConselho',
            field=models.ImageField(blank=True, null=True, upload_to='ConselhoDeliberativo', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='conselhodeliberativo',
            name='NomeConselho',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='FotoCovenio',
            field=models.ImageField(blank=True, null=True, upload_to='Convenio', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='NomeConvenio',
            field=models.CharField(default='null', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diretoriaexecutiva',
            name='CargoDiretorExecutivo',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='diretoriaexecutiva',
            name='FotoDiretorExecutivo',
            field=models.ImageField(blank=True, null=True, upload_to='DiretoriaExecutiva', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='diretoriaexecutiva',
            name='NomeDiretorExecutivo',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='FotoPremio',
            field=models.ImageField(blank=True, null=True, upload_to='Premio', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='NomePremio',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
