# Generated by Django 4.2.1 on 2023-05-10 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0049_alter_banner_fotobanner_alter_banner_nomebanner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='Duração',
        ),
        migrations.RemoveField(
            model_name='faleconosco',
            name='Nome',
        ),
        migrations.RemoveField(
            model_name='faleconosco',
            name='Sobrenome',
        ),
        migrations.RemoveField(
            model_name='faleconosco',
            name='operadora',
        ),
    ]
