# Generated by Django 4.2.1 on 2023-05-10 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0050_remove_eventos_duração_remove_faleconosco_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='Duração',
        ),
        migrations.RemoveField(
            model_name='faleconosco',
            name='Nome',
        ),
        migrations.RemoveField(
            model_name='faleconosco',
            name='Sobrenome',
        ),
        migrations.RemoveField(
            model_name='faleconosco',
            name='operadora',
        ),
    ]
