# Generated by Django 4.0.4 on 2022-05-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0003_rename_especializacao_medico_especialidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Subtitulo', models.CharField(max_length=100)),
                ('Imagem', models.ImageField(blank=True, null=True, upload_to='')),
                ('Corpo', models.TextField()),
                ('Detalhes', models.TextField()),
            ],
        ),
    ]
