# Generated by Django 4.0.4 on 2022-05-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0009_diretoria_alter_parceiros_nomeparceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomePremio', models.CharField(max_length=100)),
                ('FotoPremio', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
