# Generated by Django 4.0.4 on 2022-05-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0012_transparencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='transparencia',
            name='DataTransparencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
