# Generated by Django 4.0.4 on 2022-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalDjango', '0014_alter_banner_fotobanner_alter_convenio_fotocovenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='FotoBanner',
            field=models.ImageField(blank=True, null=True, upload_to='Banner'),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='FotoCovenio',
            field=models.ImageField(blank=True, null=True, upload_to='Convenio'),
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='FotoDiretoria',
            field=models.ImageField(blank=True, null=True, upload_to='Diretoria'),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='FotoParceiro',
            field=models.ImageField(null=True, upload_to='parceiro'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='FotoPremio',
            field=models.ImageField(blank=True, null=True, upload_to='Premio'),
        ),
    ]
